#!/usr/bin/env bash
#script that displays time fro 12h and 59 mins

hour=0
minute=1

while [ $hour -le 12 ]
do
 
while [ $minute -le 59 ]
do 
  echo "Hour: $hour, Minute: $minute"

((minute++))

done

minute=1

((hour++))
done
